language: node_js
node_js:
  - "14"
install:
  - npm install
script:
  - PORT=0 npm test
deploy:
  provider: script
  script: bash deploy-heroku.sh
  on:
    branch: master
env:
  global:
    - secure: "CH123vo8tRoxJRUIoWvlTja98VpXuxVPFcSUW7kY6EHcS80oC/hXeGwO/ql9wTTLDF2ZfSUIFeLYMJlY7sNAxQ/0ZEwVIruf2ZtLD2HrX+52pmhxnewqHoVfR+xeqgnm78zMF5Q4iYrYUCksTDkarB8nUsyzxhgaK+7sGeeLdKmRDnWP6+cmSCIdmhmx4Ezu+yCKH7LLKnK7UglHYbBLoBNxpAw4Ncvrgd9k6eh4anttye3kK0K0FBDsgZQBctOSgNg8jKP0qynbz3VeFcgVQJY3CuASlAEZoyZwUvw5m7PoM12OgWLUtmQFq63HDu8N+y7cnEMyGuYDwYzvZ2rat/+CAKqCpKYk6v7zpQwPRLI6XLXSsTGwPxCdILieoNra+SnBUw/bY4L9BjTr4FCsWD2gJLYJ40hdexFqUMIuxXZDdUcUevZn/kQ+QXXbK+262B9man63n7fdgnGT/ekr53iV4RA8WV0X93MtwSgJnAV0N5tcQBdUcv2zR+X9yuRFcFXG0VdDDmQyRGWiF6vi9mq79Rwefv334pLn0zweAum/JevA4BO1XKG8Pykbyze452souNDm2mtqbyaKTwAYGb7u0oJtEtVfx7ziTecdWmK36Wom74nDMw+CgLgzXnVIdQXjFePv5aWipHfX16TByxsfikBNlQc9bLzKSxxptpE="
